package iplanalyzer;

public enum SortField {
    AVERAGE, STRIKE_RATE, MAXIMUM_FOUR_AND_SIXES, FOUR_AND_SIXES_WITH_AVG, AVERAGE_WITH_STRIKE_RATE, MAXIMUM_RUNS_WITH_BEST_AVERAGE, ECONOMY_RATE, BEST_STRIKE_RATE_WITH_BEST_FIGURES;
}
